// Lazy-loaded JPDB v2 frequency lookup. The asset at
// /frequency/jpdb.json is generated by `npm run generate-frequency` and
// capped at rank ≤ 100,000 — anything rarer (or not in the dict) resolves
// to the `very-rare` tier with no precise rank.
//
// Schema: { "<headword>": [["<reading>"|null, rank], ...] } sorted asc by rank.

export type FrequencyTier =
  | "very-common"
  | "common"
  | "uncommon"
  | "rare"
  | "very-rare";

export interface FrequencyResult {
  rank: number | null;
  tier: FrequencyTier;
}

type RawIndex = Record<string, Array<[string | null, number]>>;

let loadPromise: Promise<RawIndex> | null = null;
let cached: RawIndex | null = null;

function load(): Promise<RawIndex> {
  if (cached) return Promise.resolve(cached);
  if (loadPromise) return loadPromise;
  loadPromise = fetch("/frequency/jpdb.json")
    .then((r) => {
      if (!r.ok) throw new Error(`jpdb.json fetch failed: ${r.status}`);
      return r.json() as Promise<RawIndex>;
    })
    .then((data) => {
      cached = data;
      return data;
    })
    .catch((err) => {
      loadPromise = null;
      throw err;
    });
  return loadPromise;
}

export function rankToTier(rank: number | null): FrequencyTier {
  if (rank === null) return "very-rare";
  if (rank <= 1500) return "very-common";
  if (rank <= 5000) return "common";
  if (rank <= 15000) return "uncommon";
  if (rank <= 30000) return "rare";
  return "very-rare";
}

export const TIER_LABEL: Record<FrequencyTier, string> = {
  "very-common": "very common",
  common: "common",
  uncommon: "uncommon",
  rare: "rare",
  "very-rare": "very rare",
};

/**
 * Lookup the JPDB frequency rank for a headword. Prefers an exact
 * (headword, reading) match; falls back to the lowest rank for any reading
 * of the headword. Returns `{rank: null, tier: "very-rare"}` for terms
 * outside the rank cap or absent from JPDB.
 */
export async function lookupFrequency(
  headword: string,
  reading: string | null
): Promise<FrequencyResult> {
  const index = await load();
  const entries = index[headword];
  if (!entries || entries.length === 0) {
    return { rank: null, tier: "very-rare" };
  }
  if (reading) {
    const match = entries.find(([r]) => r === reading);
    if (match) return { rank: match[1], tier: rankToTier(match[1]) };
  }
  // Sorted asc by rank at build time, so [0] is the most common reading.
  const best = entries[0]!;
  return { rank: best[1], tier: rankToTier(best[1]) };
}
