// Lazy-loaded JPDB v2 frequency lookup. The asset at
// /frequency/jpdb.json is generated by `npm run generate-frequency` and
// capped at rank ≤ 100,000 — anything rarer (or not in the dict) resolves
// to the `very-rare` tier with no precise rank.
//
// Schema: { "<headword>": [["<reading>"|null, rank], ...] } sorted asc by rank.

export type FrequencyTier =
  | "very-common"
  | "common"
  | "uncommon"
  | "rare"
  | "very-rare";

export interface FrequencyResult {
  rank: number | null;
  tier: FrequencyTier;
}

export interface BestFrequencyResult extends FrequencyResult {
  // The candidate orthography that produced `rank`, or null when no
  // candidate resolved.
  headword: string | null;
}

type RawIndex = Record<string, Array<[string | null, number]>>;

let loadPromise: Promise<RawIndex> | null = null;
let cached: RawIndex | null = null;

function load(): Promise<RawIndex> {
  if (cached) return Promise.resolve(cached);
  if (loadPromise) return loadPromise;
  loadPromise = fetch("/frequency/jpdb.json")
    .then((r) => {
      if (!r.ok) throw new Error(`jpdb.json fetch failed: ${r.status}`);
      return r.json() as Promise<RawIndex>;
    })
    .then((data) => {
      cached = data;
      return data;
    })
    .catch((err) => {
      loadPromise = null;
      throw err;
    });
  return loadPromise;
}

export function rankToTier(rank: number | null): FrequencyTier {
  if (rank === null) return "very-rare";
  if (rank <= 1500) return "very-common";
  if (rank <= 5000) return "common";
  if (rank <= 15000) return "uncommon";
  if (rank <= 30000) return "rare";
  return "very-rare";
}

export const TIER_LABEL: Record<FrequencyTier, string> = {
  "very-common": "very common",
  common: "common",
  uncommon: "uncommon",
  rare: "rare",
  "very-rare": "very rare",
};

/**
 * Triggers (and waits for) the one-time JPDB index fetch so subsequent
 * `lookupFrequencySync` calls are free. Idempotent — call as many times as
 * you like; resolves immediately once cached.
 */
export async function loadFrequencyIndex(): Promise<void> {
  if (cached) return;
  await load();
}

function lookupInIndex(
  index: RawIndex,
  headword: string,
  reading: string | null
): FrequencyResult {
  const entries = index[headword];
  if (!entries || entries.length === 0) {
    return { rank: null, tier: "very-rare" };
  }
  if (reading) {
    const match = entries.find(([r]) => r === reading);
    if (match) return { rank: match[1], tier: rankToTier(match[1]) };
  }
  // Sorted asc by rank at build time, so [0] is the most common reading.
  const best = entries[0]!;
  return { rank: best[1], tier: rankToTier(best[1]) };
}

/**
 * Lookup the JPDB frequency rank for a headword. Prefers an exact
 * (headword, reading) match; falls back to the lowest rank for any reading
 * of the headword. Returns `{rank: null, tier: "very-rare"}` for terms
 * outside the rank cap or absent from JPDB.
 */
export async function lookupFrequency(
  headword: string,
  reading: string | null
): Promise<FrequencyResult> {
  const index = await load();
  return lookupInIndex(index, headword, reading);
}

/**
 * Synchronous variant for callers that have already awaited
 * `loadFrequencyIndex()`. Throws if the index hasn't been fetched yet —
 * use the async `lookupFrequency` if you can't guarantee load order.
 */
export function lookupFrequencySync(
  headword: string,
  reading: string | null
): FrequencyResult {
  if (!cached) {
    throw new Error(
      "lookupFrequencySync called before loadFrequencyIndex resolved"
    );
  }
  return lookupInIndex(cached, headword, reading);
}

/**
 * One headword/rank tuple from the JPDB index, with the reading that produced
 * the rank (kana-only entries return `reading: null` since the headword itself
 * is already kana). Used by the Stats browse view to paginate top-N vocab.
 */
export interface FrequencyEntry {
  headword: string;
  reading: string | null;
  rank: number;
}

let sortedEntriesCache: FrequencyEntry[] | null = null;

/**
 * Returns every JPDB headword sorted by rank ascending, one entry per
 * headword (the lowest-rank reading wins when a headword has multiple).
 * Requires `loadFrequencyIndex()` to have resolved — throws otherwise.
 * Result is cached so subsequent calls are O(1).
 */
export function getFrequencyEntriesSync(): FrequencyEntry[] {
  if (sortedEntriesCache) return sortedEntriesCache;
  if (!cached) {
    throw new Error(
      "getFrequencyEntriesSync called before loadFrequencyIndex resolved"
    );
  }
  const out: FrequencyEntry[] = [];
  for (const [headword, entries] of Object.entries(cached)) {
    // Entries are pre-sorted asc by rank, so [0] is the lowest rank.
    const best = entries[0];
    if (!best) continue;
    out.push({ headword, reading: best[0], rank: best[1] });
  }
  out.sort((a, b) => a.rank - b.rank);
  sortedEntriesCache = out;
  return out;
}

/**
 * Lookup the best (lowest rank) JPDB frequency across multiple candidate
 * orthographies of the same word. A JMdict entry can list several kanji
 * variants (e.g. 御供え / お供え) that share a reading; JPDB indexes them
 * separately and the kanji-heaviest variant is often vastly rarer than the
 * common form the user is actually seeing in the wild. Caller-supplied order
 * doesn't matter — we pick the lowest rank among all candidates.
 *
 * Returns `{rank: null, tier: "very-rare"}` when none of the candidates
 * resolve. Deduplicates candidates internally.
 */
export async function lookupBestFrequency(
  headwords: string[],
  reading: string | null
): Promise<BestFrequencyResult> {
  const unique = Array.from(new Set(headwords.filter((h) => h.length > 0)));
  if (unique.length === 0) {
    return { rank: null, tier: "very-rare", headword: null };
  }
  const results = await Promise.all(
    unique.map((h) => lookupFrequency(h, reading))
  );
  let best: BestFrequencyResult = { rank: null, tier: "very-rare", headword: null };
  for (let i = 0; i < results.length; i++) {
    const r = results[i]!;
    if (r.rank === null) continue;
    if (best.rank === null || r.rank < best.rank) {
      best = { rank: r.rank, tier: r.tier, headword: unique[i]! };
    }
  }
  return best;
}
