// Lazy-loaded JPDB v2 frequency lookups.
//
// Two indices ship together at /frequency/:
//
// 1. `jpdb.json` — surface-keyed, generated by `npm run generate-frequency`.
//    Schema: { "<headword>": [["<reading>"|null, rank], ...] } sorted asc by
//    rank. Used as a fallback when a caller doesn't have a JMdict entry id —
//    e.g. a 1-char tap with no dictionary match.
//
// 2. `jpdb-by-entry.json` — JMdict-entry-id-keyed, generated by
//    `npm run generate-frequency-by-entry`. Schema: { "<entryId>":
//    {rank, headword, reading, canonical} }. The "headword"/"reading" pair is
//    the variant that produced the winning rank (the form the popover should
//    display); "canonical" is the JMdict k[0]/r[0] surface that the indexer
//    stamps on word_lookups / story_word_occurrences (used by VocabContext to
//    look up rank from a stamp without an IDB round-trip). The build script
//    honours JMdict's `uk` misc tag so we don't pull a homophone's rank into
//    an unrelated entry (e.g. JPDB's くらい rank belongs to the 位 "approximately"
//    suffix, not the 暗い "dark" adjective).
//
// Both are capped at rank ≤ 100,000 client-side; anything rarer falls into
// the `very-rare` tier with no precise rank.

export type FrequencyTier =
  | "very-common"
  | "common"
  | "uncommon"
  | "rare"
  | "very-rare";

export interface FrequencyResult {
  rank: number | null;
  tier: FrequencyTier;
}

export interface BestFrequencyResult extends FrequencyResult {
  // The candidate orthography that produced `rank`, or null when no
  // candidate resolved.
  headword: string | null;
}

type RawIndex = Record<string, Array<[string | null, number]>>;

interface RawEntryRecord {
  rank: number;
  headword: string;
  reading: string | null;
  canonical: string;
}
type RawEntryIndex = Record<string, RawEntryRecord>;

export interface EntryFrequencyResult extends BestFrequencyResult {
  // The reading of the winning surface (or null when the winning surface is
  // itself kana).
  reading: string | null;
}

let loadPromise: Promise<RawIndex> | null = null;
let cached: RawIndex | null = null;

let entryLoadPromise: Promise<RawEntryIndex> | null = null;
let entryCached: RawEntryIndex | null = null;
let canonicalToEntryIdCached: Map<string, string> | null = null;

function load(): Promise<RawIndex> {
  if (cached) return Promise.resolve(cached);
  if (loadPromise) return loadPromise;
  loadPromise = fetch("/frequency/jpdb.json")
    .then((r) => {
      if (!r.ok) throw new Error(`jpdb.json fetch failed: ${r.status}`);
      return r.json() as Promise<RawIndex>;
    })
    .then((data) => {
      cached = data;
      return data;
    })
    .catch((err) => {
      loadPromise = null;
      throw err;
    });
  return loadPromise;
}

function loadEntries(): Promise<RawEntryIndex> {
  if (entryCached) return Promise.resolve(entryCached);
  if (entryLoadPromise) return entryLoadPromise;
  entryLoadPromise = fetch("/frequency/jpdb-by-entry.json")
    .then((r) => {
      if (!r.ok) throw new Error(`jpdb-by-entry.json fetch failed: ${r.status}`);
      return r.json() as Promise<RawEntryIndex>;
    })
    .then((data) => {
      entryCached = data;
      // Build canonical → entryId at load time. Collisions on the canonical
      // surface (≈3% of ranked entries, e.g. 〇 spans 3 lexemes) resolve to
      // the lowest-rank entry — the most common lexeme is the most likely
      // referent of an ambiguous stamp.
      const map = new Map<string, string>();
      const bestRank = new Map<string, number>();
      for (const [id, rec] of Object.entries(data)) {
        const existing = bestRank.get(rec.canonical);
        if (existing === undefined || rec.rank < existing) {
          bestRank.set(rec.canonical, rec.rank);
          map.set(rec.canonical, id);
        }
      }
      canonicalToEntryIdCached = map;
      return data;
    })
    .catch((err) => {
      entryLoadPromise = null;
      throw err;
    });
  return entryLoadPromise;
}

export function rankToTier(rank: number | null): FrequencyTier {
  if (rank === null) return "very-rare";
  if (rank <= 1500) return "very-common";
  if (rank <= 5000) return "common";
  if (rank <= 15000) return "uncommon";
  if (rank <= 30000) return "rare";
  return "very-rare";
}

export const TIER_LABEL: Record<FrequencyTier, string> = {
  "very-common": "very common",
  common: "common",
  uncommon: "uncommon",
  rare: "rare",
  "very-rare": "very rare",
};

/**
 * Triggers (and waits for) both JPDB index fetches so subsequent sync
 * lookups are free. Idempotent — call as many times as you like; resolves
 * immediately once cached. Loads both indices in parallel since they're
 * independent assets and the second is needed by every popover/scoring
 * caller that's already awaiting the first.
 */
export async function loadFrequencyIndex(): Promise<void> {
  if (cached && entryCached) return;
  await Promise.all([load(), loadEntries()]);
}

function lookupInIndex(
  index: RawIndex,
  headword: string,
  reading: string | null
): FrequencyResult {
  const entries = index[headword];
  if (!entries || entries.length === 0) {
    return { rank: null, tier: "very-rare" };
  }
  if (reading) {
    const match = entries.find(([r]) => r === reading);
    if (match) return { rank: match[1], tier: rankToTier(match[1]) };
  }
  // Sorted asc by rank at build time, so [0] is the most common reading.
  const best = entries[0]!;
  return { rank: best[1], tier: rankToTier(best[1]) };
}

/**
 * Lookup the JPDB frequency rank for a headword. Prefers an exact
 * (headword, reading) match; falls back to the lowest rank for any reading
 * of the headword. Returns `{rank: null, tier: "very-rare"}` for terms
 * outside the rank cap or absent from JPDB.
 */
export async function lookupFrequency(
  headword: string,
  reading: string | null
): Promise<FrequencyResult> {
  const index = await load();
  return lookupInIndex(index, headword, reading);
}

/**
 * Synchronous variant for callers that have already awaited
 * `loadFrequencyIndex()`. Throws if the index hasn't been fetched yet —
 * use the async `lookupFrequency` if you can't guarantee load order.
 */
export function lookupFrequencySync(
  headword: string,
  reading: string | null
): FrequencyResult {
  if (!cached) {
    throw new Error(
      "lookupFrequencySync called before loadFrequencyIndex resolved"
    );
  }
  return lookupInIndex(cached, headword, reading);
}

/**
 * Async variant of {@link lookupFrequencyByEntrySync}. Awaits the by-entry
 * index fetch, then resolves the lookup.
 */
export async function lookupFrequencyByEntry(
  entryId: number | string
): Promise<EntryFrequencyResult | null> {
  await loadEntries();
  return lookupFrequencyByEntrySync(entryId);
}

/**
 * Look up the JPDB rank for a specific JMdict entry. This is the right call
 * for any path that has a `WordResult` in hand (popover taps, indexer): it
 * returns the rank of the variant within that entry's own (k, r) list that
 * happens to be cheapest in JPDB, with no risk of a homophone in a different
 * entry stealing the rank. Returns null when the entry id isn't in the
 * by-entry index — caller should fall back to a surface-keyed lookup.
 */
export function lookupFrequencyByEntrySync(
  entryId: number | string
): EntryFrequencyResult | null {
  if (!entryCached) {
    throw new Error(
      "lookupFrequencyByEntrySync called before loadFrequencyIndex resolved"
    );
  }
  const rec = entryCached[String(entryId)];
  if (!rec) return null;
  return {
    rank: rec.rank,
    tier: rankToTier(rec.rank),
    headword: rec.headword,
    reading: rec.reading,
  };
}

/**
 * Map an indexer stamp (the JMdict k[0] or r[0] surface) to the rank of its
 * entry. Used by VocabContext: stamps are the canonical surface, so this
 * resolves "貴方 was stamped" → entry 1223615 (the "you" pronoun) → rank 121
 * via the あなた variant, instead of the much rarer surface rank for 貴方.
 * Returns null when no entry claims the canonical surface.
 */
export function lookupFrequencyByCanonicalSync(
  canonical: string
): EntryFrequencyResult | null {
  if (!entryCached || !canonicalToEntryIdCached) {
    throw new Error(
      "lookupFrequencyByCanonicalSync called before loadFrequencyIndex resolved"
    );
  }
  const id = canonicalToEntryIdCached.get(canonical);
  if (!id) return null;
  return lookupFrequencyByEntrySync(id);
}

/**
 * One headword/rank tuple from the JPDB index, with the reading that produced
 * the rank (kana-only entries return `reading: null` since the headword itself
 * is already kana). Used by the Stats browse view to paginate top-N vocab.
 */
export interface FrequencyEntry {
  headword: string;
  reading: string | null;
  rank: number;
}

let sortedEntriesCache: FrequencyEntry[] | null = null;

/**
 * Returns every JPDB headword sorted by rank ascending, one entry per
 * headword (the lowest-rank reading wins when a headword has multiple).
 * Requires `loadFrequencyIndex()` to have resolved — throws otherwise.
 * Result is cached so subsequent calls are O(1).
 */
export function getFrequencyEntriesSync(): FrequencyEntry[] {
  if (sortedEntriesCache) return sortedEntriesCache;
  if (!cached) {
    throw new Error(
      "getFrequencyEntriesSync called before loadFrequencyIndex resolved"
    );
  }
  const out: FrequencyEntry[] = [];
  for (const [headword, entries] of Object.entries(cached)) {
    // Entries are pre-sorted asc by rank, so [0] is the lowest rank.
    const best = entries[0];
    if (!best) continue;
    out.push({ headword, reading: best[0], rank: best[1] });
  }
  out.sort((a, b) => a.rank - b.rank);
  sortedEntriesCache = out;
  return out;
}

/**
 * Lookup the best (lowest rank) JPDB frequency across multiple candidate
 * orthographies of the same word. A JMdict entry can list several kanji
 * variants (e.g. 御供え / お供え) that share a reading; JPDB indexes them
 * separately and the kanji-heaviest variant is often vastly rarer than the
 * common form the user is actually seeing in the wild. Caller-supplied order
 * doesn't matter — we pick the lowest rank among all candidates.
 *
 * Returns `{rank: null, tier: "very-rare"}` when none of the candidates
 * resolve. Deduplicates candidates internally.
 */
export async function lookupBestFrequency(
  headwords: string[],
  reading: string | null
): Promise<BestFrequencyResult> {
  const unique = Array.from(new Set(headwords.filter((h) => h.length > 0)));
  if (unique.length === 0) {
    return { rank: null, tier: "very-rare", headword: null };
  }
  const results = await Promise.all(
    unique.map((h) => lookupFrequency(h, reading))
  );
  let best: BestFrequencyResult = { rank: null, tier: "very-rare", headword: null };
  for (let i = 0; i < results.length; i++) {
    const r = results[i]!;
    if (r.rank === null) continue;
    if (best.rank === null || r.rank < best.rank) {
      best = { rank: r.rank, tier: r.tier, headword: unique[i]! };
    }
  }
  return best;
}
