-- Per-sentence TTS audio (Azure Neural TTS, generated by the
-- generate-sentence-audio Edge Function).
--
-- Storage layout in the private `sentence-audio` bucket:
--   {user_id}/story-{story_id}/{start}-{end}.mp3   source-sentence audio
--   {user_id}/chat-{chat_message_id}/{start}-{end}.mp3
--   {user_id}/cards/{card_id}.mp3                  review-card audio
--
-- Source-sentence audio has NO DB metadata: the path is deterministic from
-- (source, offsets), so object existence IS the record. That sidesteps the
-- read-modify-write race a `translations`-style JSONB merge would have.
-- Card audio is snapshotted per card (like everything else a card renders)
-- and stamped on sentence_cards.audio by the Edge Function's service role.

INSERT INTO storage.buckets (id, name, public)
VALUES ('sentence-audio', 'sentence-audio', false)
ON CONFLICT (id) DO NOTHING;

-- Users can read (and create signed URLs for) their own audio files.
-- Writes come from the Edge Function using service_role, which bypasses RLS.
CREATE POLICY "Users read own sentence audio"
  ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'sentence-audio'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- No cleanup trigger: Supabase blocks DML on storage.objects even from a
-- SECURITY DEFINER trigger (see 20260426000000). Cleanup is best-effort via
-- the Storage API instead — client-side under this DELETE policy when a
-- story/card is deleted or story content replaced, and service-role inside
-- the revise-story Edge Function when it rewrites a story body.
CREATE POLICY "Users delete own sentence audio"
  ON storage.objects FOR DELETE TO authenticated
  USING (
    bucket_id = 'sentence-audio'
    AND (storage.foldername(name))[1] = auth.uid()::text
  );

-- { path, voice, duration_ms, generated_at, version } — written only by the
-- generate-sentence-audio Edge Function (service role). NULL = no audio yet;
-- the back of the Review card offers on-demand generation.
ALTER TABLE sentence_cards ADD COLUMN audio JSONB;

-- Return-type change requires a DROP; CREATE OR REPLACE can't alter a
-- function's RETURNS TABLE shape.
DROP FUNCTION get_sentence_card_queue();

CREATE FUNCTION get_sentence_card_queue()
RETURNS TABLE (
  id BIGINT,
  story_id BIGINT,
  chat_message_id BIGINT,
  sentence_start INT,
  sentence_end INT,
  sentence_text TEXT,
  annotations JSONB,
  translation TEXT,
  box SMALLINT,
  created_at TIMESTAMPTZ,
  audio JSONB
)
LANGUAGE sql STABLE SECURITY INVOKER AS $$
  SELECT
    c.id, c.story_id, c.chat_message_id,
    c.sentence_start, c.sentence_end,
    c.sentence_text, c.annotations, c.translation,
    c.box, c.created_at, c.audio
  FROM sentence_cards c
  WHERE c.user_id = auth.uid()
    AND c.eligible_at <= now()
  ORDER BY c.eligible_at ASC, c.created_at ASC;
$$;

GRANT EXECUTE ON FUNCTION get_sentence_card_queue() TO authenticated;
